name: MolecularFoundry
main: net.guizhanss.molecularfoundry.MolecularFoundry
version: 0.1.0
api-version: 1.21
load: POSTWORLD
commands:
  molf:
    description: Molecular Foundry admin command
    usage: /molf
    permission: molecularfoundry.command
permissions:
  molecularfoundry.command:
    default: op
  molecularfoundry.menu:
    default: true
    description: Access the plugin menu
  molecularfoundry.give:
    default: op
    description: Give machine and network items
